networks:
  auth_network:
volumes:
  keycloak_pgdata:
  auth_pgdata:

services:
  keycloak:
    image: quay.io/keycloak/keycloak:22.0.0
    container_name: keycloak_auth
    command:
      - start-dev --import-realm
    environment:
      - KC_DB=postgres
      - KC_DB_URL_HOST=keycloak_db
      - KC_DB_URL_PORT=5432
      - KC_DB_URL_DATABASE=keycloak_db
      - KC_DB_USERNAME=keycloak_user
      - KC_DB_PASSWORD=q
      - KC_HEALTH_ENABLED=true
      - KC_METRICS_ENABLED=true
      - KEYCLOAK_ADMIN=admin
      - KEYCLOAK_ADMIN_PASSWORD=q
    volumes:
      - type: bind
        source: ./src/main/resources/keycloak/
        target: /opt/keycloak/data/import/
    depends_on:
      - keycloak_db
    ports:
      - "18081:8080"
    networks:
      - auth_network
  #    restart: on-failure

  keycloak_db:
    image: postgres:15.4-alpine
    container_name: keycloak_auth_db
    environment:
      - TZ=Asia/Almaty
      - POSTGRES_USER=keycloak_user
      - POSTGRES_PASSWORD=q
      - POSTGRES_DB=keycloak_db
    restart: on-failure
    ports:
      - 5434:5432
    volumes:
      - keycloak_pgdata:/var/lib/postgresql/data
    networks:
      - auth_network
#    restart: on-failure

  auth_db:
    image: postgres:14.9-alpine
    container_name: auth_db
    environment:
      - TZ=Asia/Almaty
      - POSTGRES_USER=auth_user
      - POSTGRES_PASSWORD=q
      - POSTGRES_DB=auth_db
    restart: on-failure
    ports:
      - 5435:5432
    volumes:
      - auth_pgdata:/var/lib/postgresql/data
    networks:
      - auth_network
#    restart: on-failure